# Generated by Django 3.1.3 on 2020-11-25 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('ordered_at', models.DateTimeField(verbose_name='order_timestamp')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coffeeshop.item')),
            ],
        ),
    ]
