# Generated by Django 3.1.3 on 2020-11-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0006_currentorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='CurrentOrder',
        ),
    ]
