# Generated by Django 3.1.3 on 2020-11-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0007_auto_20201126_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(verbose_name='Time Ordered'),
        ),
    ]
